default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pnp_development
  username: pnp 
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: pnp_test
